[workspace]
members = ["file-system-adaptor", "library", "memory-adaptor", "web-server"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.124"
